### ISSUE TITLE
validation code melli has error

### ISSUE THREAD

**Issue by maryamsafari2012** [anetwork/validation#1]
سلام خسته نباشید. من پکیج رو نصب کردم ولی برای کدملی هایی که با 0 شروع می شود پیغام invalid میدهد. میشه بگید چرا؟؟
مرسی

**Comment by shahrokhniakan** [comment]
!سلام با کد ملی حقیقی امتحان کنید مشکلی نداره

**Comment by maryamsafari2012** [comment]
با کد ملی خودم چک کردم. 
0013542419

```
  From: SHAHROKH <notifications@github.com>
```

 To: anetwork/validation validation@noreply.github.com 
Cc: maryamsafari2012 maryamsafari2012@yahoo.com; Author author@noreply.github.com
 Sent: Monday, 8 August 2016, 11:18:27
 Subject: Re: [anetwork/validation] validation code melli has error (#1)

!سلام با کد ملی حقیقی امتحان کنید مشکلی نداره—

**Comment by imehdihosseini** [comment]
Thank you dear @maryamsafari2012, i followed this issue there was a minor bug on this part and now everything works fine just update your package to newer one.

**Comment by maryamsafari2012** [comment]
thanks. bug fix.

Thank you dear @maryamsafari2012, i followed this issue there was a minor bug on this part and now everything works fine just update your package to newer one.—
