### ISSUE TITLE
اعتبارسنجی لیست باکس

### ISSUE THREAD

**Issue by asadghazanfary** [anetwork/validation#34]
آیا راهی برای اعتبارسنجی لیست باکس وجود دارد؟

**Comment by imehdihosseini** [comment]
@asadghazanfary  مقدار خروجی لیست باکس در نهایت به یک مقدار منتهی میشه که با الگوی فعلی این کار امکان پذیر هست، منظور شما اعتبارسنجی همه مقادیر لیست باکس هست؟ باز هم در این صورت روش متداولی برای این نوع اعتبار سنجی نیست

**Comment by asadghazanfary** [comment]
منظورم اینه که آیا از بین این متدها متدی وجود دارد که بتوان تشخیص داد که کاربر حتما یکی از مقادیر لیست باکس را انتخاب کرده است یا خیر

لطفا متدی برای تشخیص این امر معرفی نمایید.

با تشکر فراوان
