### ISSUE TITLE
error for validation

### ISSUE THREAD

**Issue by arbabi2010** [anetwork/validation#37]
when I use iran_phone or iran_mobile I get this error
Method [validateIranPhone] does not exist.
I added provider to ailias in app.php.
what's the problem

**Comment by shahrokhniakan** [comment]
@arbabi2010 Add it to providers not ailias

**Comment by arbabi2010** [comment]
ببخشید منظورم همون بود اشتباه نوشتم. فقط اضافه کردن همون provider هستش؟؟
الان بازم امتحان کردم همون مشکل رو داره

**Comment by shahrokhniakan** [comment]
@arbabi2010  use ( composer show anetwork/validation ) to check what version of package you installed please be sure you install last version.
