### ISSUE TITLE
publish language 

### ISSUE THREAD

**Issue by sedehi** [anetwork/validation#43]
فایل ترجمه زبان اعتبارسنجی ها  در کامند 
`vendor:publish`
لطفا اضافه شود که بشه متن ارور هارو ویرایش کرد

**Comment by shahrokhniakan** [comment]
@sedehi Thanks, will be added soon.

**Comment by imehdihosseini** [comment]
This issue is resolved by #44 PR, @ShahrokhNiakan sorry for reopening this issue but the issue status was unclear.
