### ISSUE TITLE
پیام اعتبارسنجی دلخواه

### ISSUE THREAD

**Issue by mgh145** [anetwork/validation#46]
موقع استفاده از پیام های اعتبارسنجی دلخواه در لاراول 5.3 پیام ها همچنان از فایل زبان که توسط پکیج نصب شده خونده میشه. لطفا بررسی کنید

$rules = [
       'name'      => 'required|persian_alpha',
       'family'    => 'required|persian_alpha'
];

$messages = [
      'name.persian_alpha'    =>  'نام باید فارسی باشد',
      'family.persian_alpha'  =>  'نام خانوادگی باید فارسی باشد'
];

$validator = Validator::make($request->all(),$rules,$messages);

**Comment by shahrokhniakan** [comment]
@mgh145 Hello dear, If you want use your custom messages you should run ( vendor:publish ) command to have custom messages of package on this path ( resources/lang/validation ) and you can change messages.

**Comment by mgh145** [comment]
ممنون از پاسخ شما .
دستور قبلا اجرا شده و پیام ها از فایلی که گفتین خونده میشه . ولی من میخوام بعضی از جاها از پیام دلخواه استفاده کنم و توی بقیه قسمت های سایت پیام ها از فایلی که گفتین خونده بشه . مشکل توی همین حالت هست که باز هم پیام هارو از فایل میخونه . در صورتی که باید پیام های داخل کد رو جایگزین کنه . لطفا این مورد رو بررسی کنین . با تشکر
