### ISSUE TITLE
مشکل جایگزینی پیام دلخواه

### ISSUE THREAD

**Issue by mgh145** [anetwork/validation#47]
ممنون از پاسخ شما .
دستوری که توی مشکل #46 گفتین قبلا اجرا شده و پیام ها از فایلی که گفتین خونده میشه . ولی من میخوام بعضی از جاها از پیام دلخواه استفاده کنم و توی بقیه قسمت های سایت پیام ها از فایلی که گفتین خونده بشه . مشکل توی همین حالت هست که باز هم پیام هارو از فایل میخونه . در صورتی که باید پیام های داخل کد رو جایگزین کنه . لطفا این مورد رو بررسی کنین . با تشکر

**Comment by shahrokhniakan** [comment]
@mgh145 I will try to solve this problem on my free time, but using this structure of package it is not possible.

**Comment by shahrokhniakan** [comment]
@mgh145 this issue solved on this version v2.0.0 of package.
