### ISSUE TITLE
Method [getCustomMessages] does not exist.

### ISSUE THREAD

**Issue by alirezahamedashki** [anetwork/validation#49]
this error occurred when i want use this package 
my code 

> $this->validate($request, [
 'name' => 'persian_alpha'
]) ; 

given this error 
Method [getCustomMessages] does not exist.

**Comment by shahrokhniakan** [comment]
Laravel version 5.4 doesn't  support getCustomMessages method. Fixed problem in this commit #50 and released version v2.1.0
