### ISSUE TITLE
مشکل اعتبار سنجی موبایل با یکتا بودن

### ISSUE THREAD

**Issue by rashcms** [anetwork/validation#51]
سلام
وقتی از iran_mobile استفاده می کنیم کاربر براحتی می تونه با فرمت های مختلف تلفن همراه عضو بشه و شرط یکتا بودن رو درو بزنه

`'mobile'   => 'required|unique:users|iran_mobile',`

چطور می تونیم ضمن پذیرش فرمت های مختلف موبایل از یکتا بودن اطمینان داشته باشیم ؟

**Comment by shahrokhniakan** [comment]
@rashcms https://laravel.com/docs/5.4/validation#rule-unique

**Comment by rashcms** [comment]
ممنون ولی اینجوری مجبوریم مثل قدیم یا یکتا بودن همه حالات رو چک کنیم یا اول ورودی کاربر رو ببریم به یک فرمت خاص بعد ثبت و بررسی کنیم و میشه دوباره کاری

**Comment by shahrokhniakan** [comment]
@rashcms This is only validation for correct format if you want to check it is unique or not in specific format you should handle it by yourself .
