### ISSUE TITLE
error in laravel 5.5 when trying to vendor:publish

### ISSUE THREAD

**Issue by amirpiri** [anetwork/validation#54]
`In QuestionHelper.php line 53:
                    
  Undefined index:  `

**Comment by shahrokhniakan** [comment]
@amirpiri Hi dear
It works for me, I tested it in Laravel ( 5.5, 5.6 ) and had no problem.
run this command :
$ php artisan vendor:publish --provider="Anetwork\Validation\PersianValidationServiceProvider"
