### ISSUE TITLE
Problem with validation

### ISSUE THREAD

**Issue by amirpiri** [anetwork/validation#55]
Method Illuminate\\Validation\\Validator::validateIranMobile does not exist.
Method Illuminate\\Validation\\Validator::validateIranPhone does not exist.

**Comment by eh3anr** [comment]
do you Add the following provider to providers part of config/app.php?
`Anetwork\Validation\PersianValidationServiceProvider::class`

**Comment by mohamadx** [comment]
@amirpiri Do you still have problem?
