### ISSUE TITLE
مشکل در نسخه 6 لاراول

### ISSUE THREAD

**Issue by mavinoo** [anetwork/validation#64]
سلام
زمان نصب روی نسخه 6 لاراول خطا میخوره
لطفا بررسی کنید

**Comment by MFakhrani** [comment]
دوستان 
میشه زودتر برای نسخه 6 لاراول این پکیج رو اصلاح کنید؟

**Comment by mohamadx** [comment]
سلام
تا یکی دو روز دیگه مشکلش رفع میشه

**Comment by mavinoo** [comment]
> سلام
> تا یکی دو روز دیگه مشکلش رفع میشه

هنوز یکی دو روز نرسیده ؟
